- name: Configure max server
  hosts: max
  become: yes

  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
    
    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Install Docker Compose via pip (alternative)
      pip:
        name: docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
      
    - name: Enable Docker to start on boot
      systemd:
        name: docker
        enabled: yes
